----

## lab_results_v2.Rmd
## 
----
## Changes:   functions, NO facets, use separate plots, save
## Tags:    ggsave,

# Medical - Historical LAB Results
# https://docs.google.com/spreadsheets/d/16PRB17uBRtferrNyVSPKHCyelTNW4I6m2bMaTcsgo7s/edit?usp=sharing

#######################
#  Variables to plot
#######################
# Tot_Cholesterol
# HDL
# LDL
# VLDL
# Trig
# GLU
# A1C
# WT

#######################
# preliminaries
# clear screen
#
```{r}
rm(list = ls())
```


# preliminary:  define functions

```{r}
.First <- function() {
    options(width=70)
    options(useFancyQuotes=FALSE)
    if (!require(lubridate)) {
        install.packages("lubridate")
    }
    if (!require(tidyverse)) {
        install.packages("tidyverse")
        require("tidyverse")
    }
    theme_set(theme_bw())
    #png <<- function(res=96, width=500, height=300, ...) 
    #   grDevices::png(res=res, width=width, height=height, ...)
}
#### ####
```


#
##################
#   Function: Read Labs
##################
```{r}
experiment <- function(){
    d<-read.csv(
        "~/Downloads/R_projects/project_health_labs/data/2016_Health Time Series_Sheet.csv",
        header = TRUE,
        na.strings = c("NA", "N/A"),  # these entries remain numbers
        # as.is=TRUE                  # not needed
        stringsAsFactors = FALSE      # do not convert to factors
    )
    
    # char to Date
    d$Date<-dmy(d$Date)
    labs<-as_tibble(d)
    return(labs)
}

```

# preliminary:  function to store tibble as .csv

```{r}
store<- function(t=tibble){
    print(result)
    f<-"./data/labs_norm.csv"
    write.csv(file= f, x=t)
    
}

```


# Main code

```{r}
# load packages
.First()

# read data
labs<-experiment()

```

###################
## Tidy
###################

```{r}
z<-labs %>%
        gather(key="Test_Names",value="Test_Result",         # create 2 new columns, and
         -c(Date,Where,Purpose,Exercise.Level,Comments,Allopurinol),na.rm=TRUE)  # except for these columns, insert all the data

result<-z %>% select(Date,Test_Names, Test_Result)
print(result,n=100)
```

# save result
```{r}
store(result)
```
#####################
## STOP
#####################


